config/routes.rb
Rails.application.routes.draw do
  devise_for :perfils, controllers: {registrations: 'registrations'}

  devise_scope :perfil do
    get 'login', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'

    authenticated :perfil do
      root 'mural#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
    
  end


  get '/perfils/show/:id', to: 'perfils#show', as: 'perfil'
  get '/perfils/:id/comments', to: 'perfils#show_comments', as: 'comments'
  get '/mural/index', to: 'mural#index' 
  post '/mural/create_comment', to: 'mural#create_comment' 

  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
    validates :content, presence: {message: "comentário não pode estar vázio"}, format: {with: /[a-zA-Z]/, message: "comentário deve possuir caracteres alfabéticos"} 

    has_one :perfil, through: :post
end

app/models/perfil.rb
class Perfil < ActiveRecord::Base
    # Include default devise modules. Others available are:
    # :lockable, :timeoutable, :trackable and  :omniauthable
    devise :database_authenticatable, :registerable,
            :recoverable, :rememberable, :validatable
    validates :name, presence:  true
    validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }, uniqueness: true 
    validates :phone, presence: true, format: { without: /[a-zA-Z]/}

    has_many :posts
    has_many :comments, through: :posts
    
end

app/models/post.rb
class Post < ApplicationRecord
    validates :titulo, presence: { message: "é um campo obrigatório!" }, format: { with: /[a-zA-Z]/, message: "deve possuir caracteres alfabéticos!" }
    validates :descricao, presence: { message: "é um campo obrigatório!" }, format: { with: /[a-zA-Z]/, message: "deve possuir caracteres alfabéticos!" } 
    validates :local, presence: { message: "é um campo obrigatório!" }, format: { with: /[a-zA-Z]/, message: "deve possuir caracteres alfabéticos!" } 
    validates :curtidas, :numericality => { :greater_than_or_equal_to => 0 }

    has_many :comments, dependent: :destroy
    belongs_to :perfil
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_perfil!, except: %i[]
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :phone])
        devise_parameter_sanitizer.permit(:account_update, keys: [:name, :phone])
    end

    def index
    end
end

app/controllers/mural_controller.rb
class MuralController < ApplicationController
  def index
    @posts = nil
    if params[:encontrado] == 'true'
      @posts = Post.where(encontrado:'1')
    else
      @posts = Post.all
    end
    @comment = Comment.new
  end

  def create_comment
    @comment = Post.find_by(id: comment_params[:post]).comments.create(content: comment_params[:content], perfil_id: current_perfil.id)
    @posts = Post.all
    render :index, status: :unprocessable_entity, content_type: "text/html"
    headers["Content-Type"] = "text/html"
  end

  private def comment_params 
    params.require(:comment).permit(:content, :post)
  end
end

app/controllers/perfils_controller.rb
class PerfilsController < ApplicationController
   
    def show
        @perfil = Perfil.find(params[:id])
    end

    def show_comments
        @perfil = Perfil.find(params[:id])
        @comments = Comment.where(perfil_id: @perfil.id)
    end
    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_perfil!

    def new
        @post = Post.new
    end

    def create
        if current_perfil
            @post = current_perfil.posts.create(post_params.merge(perfil: current_perfil))
            if @post.valid?
                redirect_to @post
            else
                render :new, status: :unprocessable_entity, content_type: "text/html"
                headers["Content-Type"] = "text/html"
            end
        end
    end

    def edit
        @post = Post.find(params[:id])
    end

    def destroy
        puts("CHAMOU O DELETAAAAAAAAR <<<<<<<<<<<<<<<")
        @post = Post.find(params[:id])
        @post.destroy
        respond_to do |format|
            format.html { redirect_to mural_index_url, notice: "Post deletado com sucesso!" }
        end
    end

    def edit
        @post = Post.find(params[:id])
    end

    def update
        @post = Post.find(params[:id])
        respond_to do |format|
            if has_new_likes(post_params, @post) && @post.update(post_params)
                format.html { redirect_to mural_index_url, notice: "O post foi curtido com sucesso." }
            else 
                if @post.update(post_params)
                    format.html { redirect_to post_url(@post), notice: "O post foi editado com sucesso." }
                    format.json { render :show, status: :ok, location: @classroom }
                else
                    format.html { render :edit, status: :unprocessable_entity }
                    format.json { render json: @post.errors, status: :unprocessable_entity }
                end
            end
        end
    end

    def show
        @post = Post.find(params[:id])
    end

    def post_params 
        params.require(:post).permit(:titulo, :descricao, :tipo, :local, :encontrado, :curtidas)
    end

    def has_new_likes(post_params, post)
        return post.curtidas < (post_params[:curtidas].nil? ? 0 : post_params[:curtidas]).to_i
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  

  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  def edit
    @posts = current_perfil.posts
    super
  end

  def update
    @posts = current_perfil.posts
    super
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mural_helper.rb
module MuralHelper
end

app/helpers/perfil_helper.rb
module PerfilHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/application/index.html.erb
<h1>Olá!</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
    <script src="https://code.jquery.com/jquery-1.9.1.js"></script>
  </head>

  <%= content_tag :body, data: { action: action_name, controller: controller_name} do %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  <% end %>
</html>

app/views/mural/index.html.erb
<div>
    <% if perfil_signed_in? %>
      <%= link_to 'Meu Perfil', edit_perfil_registration_path, :class => 'navbar-link' %> 
      <%= link_to "Novo Post", new_post_path, :class => 'navbar-link'  %>
    <% end %>
</div>

<h1>Mural</h1>

<!-- Caso nao exista posts -->
<% if !@posts.any? %>
    <p>
        Nenhum post cadastrado por enquanto.
    </p>
<% end %>

<!-- #Caso exista post-->
<div id="posts">
    <% if request.url.include? 'encontrado' %>
        <% if request.url.include? 'false' %>
            <%= link_to 'Mostrar apenas pets já encontrados', mural_index_path(:encontrado=>true), :class => 'navbar-link' %> 
        <%else%>
            <%= link_to 'Mostrar todos os pets', mural_index_path(:encontrado=>false), :class => 'navbar-link' %> 
        <%end%>    
    <%else%>
        <p>asfsadfasdfasdg</p>
        <%= link_to 'Mostrar apenas pets já encontrados', mural_index_path(:encontrado=>true), :class => 'navbar-link' %> 
    <%end%>

    <%@posts.each do |post|%>
        <%= render 'posts/post', post: post %>
    <%end%>
    <% if @comment.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@comment.errors.count, "erro") %> impedem que o comentario seja gravado no banco de dados:</h2>
        
            <ul>
                <% @comment.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
</div>

app/views/perfils/show.html.erb
<h2>Perfil</h2>

<p>
<strong>Nome:</strong>
<%= @perfil.name %>
</p>

<p>
<strong>Email:</strong>
<%= @perfil.email %>
</p>

<p>
<strong>Telefone:</strong>
<%= @perfil.phone %>
</p>

app/views/perfils/show_comments.html.erb
<h2>Comentários de <%= @perfil.name %></h2>
<% if @comments.length() > 0 %>
    <div id="comments">
        <%@comments.each do |comment|%>
            <div id="comment">
                <%= link_to "Post de "+comment.post.perfil.name, '/posts/' + comment.post.id.to_s %>
                <p>Comentário <%= comment.content %></p>
            </div>
        <%end%>
    </div>
<% else %>
    <p>Ainda não há comentários deste usuário.</p>
<% end %>

app/views/posts/_post.html.erb
<div>

    <p>
    <strong>Autor:</strong>
    <%= link_to post.perfil.name, perfil_path(post.perfil) %>
    </p>

    <p>
    <strong>Título:</strong>
    <%= post.titulo %>
    </p>
    
    <p>
    <strong>Descrição:</strong>
    <%= post.descricao %>
    </p>

    <p>
    <strong>Tipo:</strong>
    <%= post.tipo %>
    </p>

    <p>
    <strong>Local:</strong>
    <%= post.local %>
    </p>

    <p>
    <%= post.curtidas.nil? ? 0 : post.curtidas %> Curtida(s)
    </p>

    <p>
    <strong>Criado em:</strong>
    <%= post.created_at.strftime("%d / %m / %Y") %>
    </p>

    <% if current_perfil == post.perfil%>
        <%=link_to "Editar post", edit_post_path(post.id) %>
    <% end %>
    
    <% if post.encontrado == '1' %>
        <p>PET ENCONTRADO</p>
    <% end %>

    <%= form_with scope: :post, url: post_url(id: post.id), method: :patch do |form|%>
        <%= form.hidden_field :titulo, :value => post.titulo %>
        <%= form.hidden_field :descricao, :value => post.descricao %>
        <%= form.hidden_field :local, :value => post.local %>
        <%= form.hidden_field :tipo, :value => post.tipo %>
        <%= form.hidden_field :encontrado, :value => post.encontrado %> 
        <%= form.hidden_field :curtidas, :value => post.curtidas.nil? ? 1 : post.curtidas + 1 %>

        <p>
            <%= form.submit 'Curtir' %>
        </p>
    <% end %>

    <!-- Comments Listing -->
    <% if post.comments.length > 0 %>
        <%= link_to 'Esconder/mostrar comentários', '', class: 'hide', data: {'comment_section_id' => 'comment_section_'+ post.id.to_s }, id: 'hide_comments' %>
        <div class='comment' id="<%= 'comment_section_' + post.id.to_s %>">
            <ul style="margin-left: 5%">
                <% post.comments.each do |comment| %>
                    <li>Nome: <%=comment.perfil.name%> Criado em: <%= comment.created_at.strftime("%d/%m/%Y") %><br/>Comentário: <%= comment.content %></li>
                <% end %>
            </ul>
        </div>
    <% else %>
        <p>Este post não possui comentários!</p>
    <% end %>

    <!-- Comment Input Field -->
    <%= form_with scope: :comment, url: mural_create_comment_path, local: true do |form| %>

        <p>
            <%= form.label "Comente:" %><br>
            <%= form.text_area :content, { :id => 'Comentario' } %>
        </p>
        <p>
            <%= form.number_field :post, id: :post,  value: post.id, type: :hidden %>
        </p>
        <p>
            <%= form.submit 'Enviar' %>
        </p>

    <% end %>
</div>

app/views/posts/edit.html.erb
<h1>Edição de Post</h1>

<% if @post.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@post.errors.count, "erro") %> impedem que o post seja gravados no banco de dados:</h2>
 
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @post) do |form| %>
  <p>
    <%= form.label :titulo %><br>
    <%= form.text_field :titulo %>
  </p>
 
  <p>
    <%= form.label :descricao %><br>
    <%= form.text_field :descricao %>
  </p> 

  <p>
    <%= form.label :local %><br>
    <%= form.text_field :local %>
  </p> 

  <p>
    <b>Você perdeu ou encontrou um pet?</b>
      <%= form.radio_button :tipo, 'perdido', :checked => true %> Pet perdido
      <%= form.radio_button :tipo, 'encontrado' %> Pet encontrado<br />
  </p>
  
  <p>
    <b>Este pet foi encontrado por você (caso tenha perdido) ou pelo dono (caso tenha encontrado)?</b>
      <%= form.check_box :encontrado %> Sim
  </p>

  <%= form.hidden_field :curtidas, :value => @post.curtidas.nil? ? 0 : @post.curtidas %>

  <p>
    <%= form.submit 'Editar' %>
  </p>

<% end %>

<%= button_to "Deletar post", post_path(@post.id), :method => :delete %>

app/views/posts/new.html.erb
<h1>Novo Post</h1>

<% if @post.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@post.errors.count, "erro") %> impedem que o post seja gravados no banco de dados:</h2>
 
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with scope: :post, url: posts_path, local: true do |form| %>
  <p>
    <%= form.label :titulo %><br>
    <%= form.text_field :titulo %>
  </p>
 
  <p>
    <%= form.label :local %><br>
    <%= form.text_field :local %>
  </p>
 
  <p>
    <%= form.label :descricao %><br>
    <%= form.text_field :descricao %>
  </p>
  
  <%= form.hidden_field :curtidas, :value => 0 %>

  <p>
    <b>Você perdeu ou encontrou um pet?</b>
      <%= form.radio_button :tipo, 'perdido', :checked => true %> Pet perdido
      <%= form.radio_button :tipo, 'encontrado' %> Pet encontrado<br />
  </p>

  <p>
    <%= form.submit 'Criar novo post' %>
  </p>
<% end %>

app/views/posts/show.html.erb
<h2>Post</h2>

<p>
  <strong>Título:</strong>
  <%= @post.titulo %>
</p>
 
<p>
  <strong>Descrição:</strong>
  <%= @post.descricao %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @post.tipo %>
</p>

<p>
  <strong>Local:</strong>
  <%= @post.local %>
</p>

<p>
  <strong>Criado em:</strong>
  <%= @post.created_at.strftime("%d / %m / %Y") %>
</p>


<% if @post.encontrado == '1' %>
  <p>PET ENCONTRADO</p>
<% end %>

<%= link_to 'Voltar para o mural', mural_index_path, :class => 'navbar-link' %> 